name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Instalar dependências
        run: npm install

      - name: Corrigir permissões dos binários
        run: chmod +x node_modules/.bin/mocha

      - name: Esperar as APIs estarem Funcionando
        run: sleep 8

      - name: Criar .env
        run: |
          echo "BASE_URL_REST=${{ secrets.BASE_URL_REST }}" >> .env

      - name: Executar testes controller
        run: npx mocha test/rest/controller/**/*.test.js --timeout 10000 --reporter mochawesome

      - name: Executar testes external
        run: npx mocha test/rest/external/**/*.test.js --timeout 10000 --reporter mochawesome
